#!/usr/bin/env bun
import { homedir } from "node:os";
import { join } from "node:path";
import { appendFileSync, mkdirSync, readFileSync, existsSync } from "node:fs";
import { dirname } from "node:path";
import type { CanonicalEvent } from "../orch-monitor/lib/canonical-event.ts";
import { loadForwarderConfig } from "./lib/config.ts";
import { readCheckpoint, writeCheckpoint } from "./lib/checkpoint.ts";
import { createTailer } from "./lib/tail.ts";
import { log } from "./lib/logger.ts";
import { logDaemonHeartbeat } from "../lib/daemon-heartbeat.mjs";
import { emitProcessMemoryMetric } from "../lib/process-memory-metric.mjs"; // CTL-1517: per-process RSS/heap gauge
import { OtlpSender } from "./lib/destinations/otlp.ts";
import { PosthogSender } from "./lib/destinations/posthog.ts";
import { CloudflareAESender } from "./lib/destinations/cloudflare-ae.ts";
import {
  isFlatEvent,
  normalizeFlatEvent,
  isPinoRecord,
  normalizePinoRecord,
} from "./lib/normalize.ts";
import { dlqDepth } from "./lib/dlq.ts";
import { buildCanonicalEnvelope } from "./lib/canonical.ts";

const CATALYST_DIR = process.env.CATALYST_DIR ?? join(homedir(), "catalyst");
const EVENTS_DIR = process.env.CATALYST_EVENTS_DIR ?? join(CATALYST_DIR, "events");
const CHECKPOINT_PATH = join(CATALYST_DIR, "otel-forward.checkpoint.json");
// CTL-1506 (Codex P1): the project key's authoritative source is Layer-1
// .catalyst/config.json (`catalyst.projectKey`), which links to the Layer-2
// config-{projectKey}.json. Resolve it in precedence order — CATALYST_PROJECT_KEY env
// override → Layer-1 key → default — so a non-default key works under the normal
// `catalyst-monitor.sh forward-start` path (which exports no env var). Absent/malformed
// Layer-1 file falls back safely to the default.
function findLayer1Config(): string | null {
  // CTL-1506 (Codex #2742 P1): resolve INDEPENDENTLY of the working directory first.
  // The supported service path has no meaningful cwd — the LaunchAgent generated by
  // catalyst-stack sets no WorkingDirectory and catalyst-monitor.sh forwards no
  // project/config override — so under launchd the ancestor walk below starts from
  // whatever launchd chose (typically /), finds nothing, and every non-default project
  // silently resolved to `catalyst-workspace` and loaded the WRONG Layer-2 file.
  //
  // Honor the repo's established pin, precedence CATALYST_CONFIG_FILE >
  // CATALYST_CONFIG_PATH > cwd walk — the same order config-path.ts (orch-monitor),
  // catalyst-execution-core and catalyst-monitor.sh already document and use, so a
  // caller that pins one var gets identical behavior across every daemon.
  for (const envVar of ["CATALYST_CONFIG_FILE", "CATALYST_CONFIG_PATH"]) {
    const pinned = process.env[envVar];
    if (pinned && existsSync(pinned)) return pinned;
  }
  // CATALYST_DIR-relative candidate: correct under launchd, where cwd is meaningless
  // but CATALYST_DIR is always set (or defaulted to ~/catalyst above).
  const dirCandidate = join(CATALYST_DIR, ".catalyst/config.json");
  if (existsSync(dirCandidate)) return dirCandidate;
  // Walk up from cwd — forward-start may be invoked from a repo subdirectory, so an
  // exact-cwd lookup would miss the repo-root .catalyst/config.json (Codex P2).
  let dir = process.cwd();
  for (let i = 0; i < 40; i++) {
    const p = join(dir, ".catalyst/config.json");
    if (existsSync(p)) return p;
    const parent = dirname(dir);
    if (parent === dir) break; // reached filesystem root
    dir = parent;
  }
  return null;
}
// CTL-1506 (Codex #2742 P1): record WHY the key resolved as it did, so the default is
// never silently indistinguishable from a real answer. Loading the wrong Layer-2 config
// degrades quietly (wrong endpoint/token) — exactly the class of failure that should be
// loud. Logged once at startup, after the logger exists.
let projectKeySource = "default";
function resolveProjectKey(): string {
  if (process.env.CATALYST_PROJECT_KEY) {
    projectKeySource = "env:CATALYST_PROJECT_KEY";
    return process.env.CATALYST_PROJECT_KEY;
  }
  const l1Path = findLayer1Config();
  if (l1Path) {
    try {
      const l1 = JSON.parse(readFileSync(l1Path, "utf8"));
      const key = l1?.catalyst?.projectKey;
      if (typeof key === "string" && key) {
        projectKeySource = `layer1:${l1Path}`;
        return key;
      }
      projectKeySource = `layer1-no-key:${l1Path}`;
    } catch {
      projectKeySource = `layer1-malformed:${l1Path}`;
    }
  } else {
    projectKeySource = "no-layer1-found";
  }
  return "catalyst-workspace";
}
const PROJECT_KEY = resolveProjectKey();
// Derive the Layer-2 path from the resolved project key (config-{projectKey}.json),
// still overridable wholesale via CATALYST_CONFIG_PATH.
const CONFIG_PATH =
  process.env.CATALYST_CONFIG_PATH ??
  join(homedir(), `.config/catalyst/config-${PROJECT_KEY}.json`);

const cfg = loadForwarderConfig(CONFIG_PATH, PROJECT_KEY);
const ck = readCheckpoint(CHECKPOINT_PATH);

let stats = { processed: 0, skipped: 0 };

// CTL-1060 Phase 3: lag tracking state. lastLocalTs = newest event ts seen from the log.
// lastForwardedTs = newest event ts confirmed delivered to OTLP/Loki (seeded from checkpoint).
let lastLocalTs: string | undefined;
let lastForwardedTs: string | undefined = ck?.lastForwardedTs;

// 30-second cadence for forward_lag canonical events (CTL-1060 Phase 3).
// Tied to the OTLP/Loki path — this is the path the 2026-06-11 audit reported as "0 in Loki".
const LAG_EMIT_MS = 30_000;

/** Returns max of two ISO-8601 timestamps (or b when a is undefined). */
export function maxTs(a: string | undefined, b: string | undefined): string | undefined {
  if (!a) return b;
  if (!b) return a;
  return a >= b ? a : b;
}

/** Returns lagMs = localNewestTs - lastForwardedTs in ms, clamped to ≥ 0. Returns 0 when either timestamp is undefined. */
export function computeLagMs(
  localNewestTs: string | undefined,
  lastForwardedTs: string | undefined
): number {
  if (!localNewestTs || !lastForwardedTs) return 0;
  const delta = Date.parse(localNewestTs) - Date.parse(lastForwardedTs);
  return delta > 0 ? delta : 0;
}

/** Builds a canonical catalyst.observability.forward_lag event for the broker/HUD pipeline. */
export function buildLagEvent(opts: {
  localNewestTs: string | undefined;
  lastForwardedTs: string | undefined;
  dlqDepth: number;
}): CanonicalEvent {
  return buildCanonicalEnvelope({
    serviceName: "catalyst.otel-forward",
    eventName: "catalyst.observability.forward_lag",
    payload: {
      lagMs: computeLagMs(opts.localNewestTs, opts.lastForwardedTs),
      localNewestTs: opts.localNewestTs,
      lastForwardedTs: opts.lastForwardedTs,
      dlqDepth: opts.dlqDepth,
    },
  });
}

const buffers: { otlp: CanonicalEvent[]; posthog: CanonicalEvent[]; cae: CanonicalEvent[] } = {
  otlp: [],
  posthog: [],
  cae: [],
};

const CURRENT_MONTH = () => {
  const now = new Date();
  return `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, "0")}`;
};
// CTL-1506 (Codex P2): resolve the monthly log file on each use, not once at startup —
// a daemon that crosses a UTC month boundary must write to the file the tailer now reads.
const currentEventLogPath = () => join(EVENTS_DIR, `${CURRENT_MONTH()}.jsonl`);

const OTLP_DLQ_PATH = join(CATALYST_DIR, "otel-forward-dlq-otlp.jsonl");

// CTL-1506 (Codex P1): module-scoped so senders can carry the shutdown signal — an
// aborted flush stops retrying and DLQs immediately, keeping shutdown inside the
// launcher's SIGKILL grace. The SIGTERM/SIGINT handlers below (in the main block) abort it.
const ac = new AbortController();

const senders = {
  otlp: cfg.otlp.enabled
    ? new OtlpSender({
        endpoint: cfg.otlp.endpoint,
        dlqPath: OTLP_DLQ_PATH,
        eventLogPath: currentEventLogPath,
        signal: ac.signal,
        // CTL-1506: age window + retry window from config
        lokiAcceptWindowMs: cfg.otlp.lokiAcceptWindowMs,
        httpRetryPolicy: { maxElapsedMs: cfg.otlp.maxRetryElapsedMs },
        // CTL-1060 Phase 3: advance lastForwardedTs on each confirmed-delivered batch.
        // CTL-1506 (Codex P2): only fold PARSEABLE timestamps into the watermark — an
        // unparseable ts (e.g. "not-a-date") is lexicographically larger than an ISO
        // string, so maxTs would pin lastForwardedTs to it, computeLagMs would then read
        // NaN (treated as 0), and forward-lag reporting would be silently suppressed —
        // persisted across restart via the checkpoint.
        onBatchDelivered: (batch) => {
          const batchMaxTs = batch.reduce((acc, ev) => {
            const t = (ev as CanonicalEvent).ts;
            return t && !Number.isNaN(Date.parse(t)) ? maxTs(acc, t) : acc;
          }, undefined as string | undefined);
          lastForwardedTs = maxTs(lastForwardedTs, batchMaxTs);
        },
      })
    : null,
  posthog: cfg.posthog.enabled
    ? new PosthogSender({
        apiKey: cfg.posthog.apiKey,
        host: cfg.posthog.host,
        dlqPath: join(CATALYST_DIR, "otel-forward-dlq-posthog.jsonl"),
      })
    : null,
  cae: cfg.cloudflareAE.enabled
    ? new CloudflareAESender({
        accountId: cfg.cloudflareAE.accountId,
        apiToken: cfg.cloudflareAE.apiToken,
        dataset: cfg.cloudflareAE.dataset,
        dlqPath: join(CATALYST_DIR, "otel-forward-dlq-cae.jsonl"),
      })
    : null,
};

function emitLag(): void {
  // CTL-1280: deterministic liveness heartbeat to otel-forward.log (Alloy→Loki),
  // emitted UNCONDITIONALLY each tick — BEFORE the cold-start skip below — so an
  // idle/quiet forwarder still proves it is alive (it previously wrote only a
  // startup line then went silent, reading as down). Rides the Alloy .log stream,
  // independent of the event pipeline this daemon itself ships.
  logDaemonHeartbeat(log, "otel-forward");
  // CTL-1517: per-process RSS/heap OTel gauge on the same tick (fire-and-forget; never
  // throws, never blocks) so per-daemon memory becomes attributable in Prometheus.
  void emitProcessMemoryMetric({ serviceName: "catalyst.otel-forward", log });
  // Skip on cold start before any event has been processed or delivered
  if (!lastLocalTs && !lastForwardedTs) return;
  try {
    const ev = buildLagEvent({
      localNewestTs: lastLocalTs,
      lastForwardedTs,
      dlqDepth: dlqDepth(OTLP_DLQ_PATH),
    });
    const logPath = currentEventLogPath(); // CTL-1506: resolve per emission (month rollover)
    mkdirSync(dirname(logPath), { recursive: true });
    appendFileSync(logPath, JSON.stringify(ev) + "\n");
  } catch {
    // Best-effort — must never throw
  }
}

export function processLine(line: string): void {
  try {
    let ev = JSON.parse(line) as CanonicalEvent;
    // pino BEFORE flat: an execution-core pino WARN/ERROR may carry a structured
    // `event` field (e.g. reaper.mjs), which isFlatEvent would otherwise claim
    // and strip of its severity. isPinoRecord (numeric level + string msg) never
    // matches a real flat catalyst event, so this ordering is safe (CTL-1424).
    if (isPinoRecord(ev)) ev = normalizePinoRecord(ev as unknown as Record<string, unknown>);
    else if (isFlatEvent(ev)) ev = normalizeFlatEvent(ev as unknown as Record<string, unknown>);
    if (!ev.attributes) {
      stats.skipped++;
      return;
    }
    stats.processed++;
    // Track newest local event timestamp for lag metric (CTL-1060 Phase 3).
    // CTL-1506 (Codex P2): guard parseability so a malformed ts can't poison the watermark.
    if (ev.ts && !Number.isNaN(Date.parse(ev.ts))) lastLocalTs = maxTs(lastLocalTs, ev.ts);
    if (senders.otlp) buffers.otlp.push(ev);
    if (senders.posthog) buffers.posthog.push(ev);
    if (senders.cae) buffers.cae.push(ev);
  } catch {
    stats.skipped++;
  }
}

export function getStats() {
  return { ...stats };
}

// CTL-1506 (Codex #2742 P1): the checkpoint-advance decision, extracted pure so the
// "never persist past in-memory events" invariant is unit-testable rather than buried in
// the timer. Returns the position to persist: the live read position ONLY when every
// destination is drained (buffered events flushed AND no flush in flight — a resolved
// flush means durable, delivered or DLQ'd); otherwise the previous durable position,
// unchanged. Monotonic within a file: never returns an offset lower than `prev` for the
// same path, so a transient drain can't rewind the checkpoint.
export function nextDurableCheckpoint(args: {
  drained: boolean;
  currentPath: string;
  currentOffset: number;
  prevPath: string;
  prevOffset: number;
}): { path: string; offset: number } {
  const { drained, currentPath, currentOffset, prevPath, prevOffset } = args;
  if (!drained) return { path: prevPath, offset: prevOffset };
  // Rotated to a new file → adopt it outright (offsets are per-file, not comparable).
  if (currentPath !== prevPath) return { path: currentPath, offset: currentOffset };
  return { path: currentPath, offset: Math.max(prevOffset, currentOffset) };
}

type DestKey = "otlp" | "posthog" | "cae";

// CTL-1506 (Codex P1/P2): serialize each destination's flushes INDEPENDENTLY. A sender's
// flush() opens a retry window up to maxRetryElapsedMs (default 60 s) while the flush
// timer fires far more often. A PER-DESTINATION in-flight guard keeps OTLP's DLQ access
// race-free (no two OtlpSender.flush concurrently entering drainDlqBounded against the
// same file) WITHOUT coupling healthy sinks to a slow one — a tick for PostHog/CFAE
// still flushes while OTLP is mid-retry, so their events don't sit in memory (which,
// with the checkpoint advancing, a restart could otherwise skip).
const inFlight: Record<DestKey, Promise<void> | null> = { otlp: null, posthog: null, cae: null };

function flushDest(
  key: DestKey,
  sender: { flush: (b: CanonicalEvent[]) => Promise<void> } | null,
  buffer: CanonicalEvent[]
): Promise<void> {
  if (!sender || buffer.length === 0) return Promise.resolve();
  if (inFlight[key]) return inFlight[key]!; // coalesce this destination's tick
  // CTL-1506: drain the whole buffer in a single flush() so the sender's own DLQ drain
  // runs exactly once per cycle (CTL-1060 per-cycle cap) and no spliced-out remainder can
  // be lost. batchSize is advisory only — see the config reference. A sender.flush() never
  // rejects in normal operation (it DLQs its own failures); the timer .catch below is the
  // backstop for an exceptional storage error.
  const p = sender.flush(buffer.splice(0)).finally(() => {
    inFlight[key] = null;
  });
  inFlight[key] = p;
  return p;
}

async function flushAll(): Promise<void> {
  await Promise.allSettled([
    flushDest("otlp", senders.otlp, buffers.otlp),
    flushDest("posthog", senders.posthog, buffers.posthog),
    flushDest("cae", senders.cae, buffers.cae),
  ]);
}

if (import.meta.main) {
  process.on("SIGTERM", () => {
    ac.abort();
  });
  process.on("SIGINT", () => {
    ac.abort();
  });

  const tailer = createTailer({
    eventsDir: EVENTS_DIR,
    offset: ck?.offset ?? 0,
    onLine: processLine,
    signal: ac.signal,
  });

  // CTL-1506 (Codex P2): one timer PER enabled destination at its OWN flushIntervalMs,
  // so a per-forwarder cadence actually takes effect (the old single global-min timer
  // flushed every sink at the fastest configured interval).
  // CTL-1506 (Codex P1): each timer swallows its flush rejection (logs it) — Bun treats an
  // unhandled promise rejection as fatal, so a storage/DLQ error in one destination must
  // not take down the whole daemon (the old global timer consumed rejections via allSettled).
  const onFlushError = (dest: string) => (err: unknown) =>
    log.error({ dest, err: err instanceof Error ? err.message : String(err) }, "scheduled flush failed");
  const flushTimers: ReturnType<typeof setInterval>[] = [];
  if (senders.otlp) {
    flushTimers.push(setInterval(() => {
      flushDest("otlp", senders.otlp, buffers.otlp).catch(onFlushError("otlp"));
    }, cfg.otlp.flushIntervalMs));
  }
  if (senders.posthog) {
    flushTimers.push(setInterval(() => {
      flushDest("posthog", senders.posthog, buffers.posthog).catch(onFlushError("posthog"));
    }, cfg.posthog.flushIntervalMs));
  }
  if (senders.cae) {
    flushTimers.push(setInterval(() => {
      flushDest("cae", senders.cae, buffers.cae).catch(onFlushError("cae"));
    }, cfg.cloudflareAE.flushIntervalMs));
  }

  // CTL-1506 (Codex #2742 P1): the checkpoint must never advance PAST events that are
  // still only in memory. tailer.currentOffset() is the READ position; an event is not
  // durable until its destination's flush() resolves (delivered, or DLQ'd — the sender
  // DLQs its own failures, so a resolved flush means durable either way). While OTLP is
  // inside its retry window (default 60 s) flushDest coalesces every tick onto the
  // existing promise and the buffer keeps growing — yet this timer was persisting an
  // ever-advancing offset. A hard crash in that window resumed from beyond those events,
  // dropping them permanently.
  //
  // Fix: only advance the persisted offset at moments when EVERY destination is fully
  // drained (no buffered events, no flush in flight). Between such moments the previous
  // floor is re-persisted, so a crash replays from the last provably-durable position.
  // Deliberately conservative: a stalled sink holds the floor back, which costs replayed
  // (duplicate) events on restart rather than lost ones — the correct direction for an
  // observability forwarder, and the direction the DLQ already assumes.
  let durableOffset = ck?.offset ?? 0;
  let durablePath = ck?.path ?? tailer.currentPath();
  const allDrained = () =>
    buffers.otlp.length === 0 &&
    buffers.posthog.length === 0 &&
    buffers.cae.length === 0 &&
    !inFlight.otlp &&
    !inFlight.posthog &&
    !inFlight.cae;

  const ckTimer = setInterval(() => {
    const next = nextDurableCheckpoint({
      drained: allDrained(),
      currentPath: tailer.currentPath(),
      currentOffset: tailer.currentOffset(),
      prevPath: durablePath,
      prevOffset: durableOffset,
    });
    durablePath = next.path;
    durableOffset = next.offset;
    writeCheckpoint(CHECKPOINT_PATH, { path: durablePath, offset: durableOffset, lastForwardedTs });
  }, 10_000);

  // CTL-1060 Phase 3: emit forward_lag canonical event every 30 s.
  const lagTimer = setInterval(emitLag, LAG_EMIT_MS);

  // CTL-1506 (Codex #2742 P1): surface the project-key provenance. When it fell back to
  // the default WITHOUT a Layer-1 file, warn — under launchd that is the signature of a
  // non-default project silently loading the wrong Layer-2 config.
  if (projectKeySource === "default" || projectKeySource.startsWith("no-layer1")) {
    log.warn(
      { projectKey: PROJECT_KEY, source: projectKeySource, cwd: process.cwd(), catalystDir: CATALYST_DIR },
      "project key fell back to the default — no Layer-1 config found; pin CATALYST_CONFIG_FILE if this is not the intended project"
    );
  } else {
    log.info({ projectKey: PROJECT_KEY, source: projectKeySource }, "project key resolved");
  }

  log.info(
    {
      otlpEnabled: cfg.otlp.enabled,
      posthogEnabled: cfg.posthog.enabled,
      cfaeEnabled: cfg.cloudflareAE.enabled,
    },
    "started"
  );

  await tailer.run();

  for (const t of flushTimers) clearInterval(t);
  clearInterval(ckTimer);
  clearInterval(lagTimer);
  // CTL-1506 (Codex P1): shutdown is BOUNDED. ac.abort() (from the SIGTERM/SIGINT handlers)
  // makes any in-flight retry stop and DLQ, and flushAll drains each buffer in one pass
  // (each retry now aborts fast → DLQ), so this completes well inside the launcher's grace
  // instead of waiting out a full 60s retry window.
  await Promise.allSettled(Object.values(inFlight).filter((p): p is Promise<void> => p !== null));
  // CTL-1506 (Codex #2742 P1): after the bounded drain above, everything read is durable,
  // so persist the true read position. Without this the conservative floor would make a
  // CLEAN shutdown replay its last buffered batch on every restart.
  if (allDrained()) {
    writeCheckpoint(CHECKPOINT_PATH, {
      path: tailer.currentPath(),
      offset: tailer.currentOffset(),
      lastForwardedTs,
    });
  }
  await flushAll();
  log.info({ processed: stats.processed, skipped: stats.skipped }, "stopped");
}
